(async()=>{
  const baseText=await (await fetch('site-v11.js?rev=20260811v12base',{cache:'no-store'})).text();
  const baseRun=(0,eval)(baseText);
  if(baseRun&&typeof baseRun.then==='function') await baseRun;

  const style=document.createElement('style');
  style.textContent=`
  .identity-v12{padding:30px 0 38px;background:#0b2744;color:#fff;border-top:1px solid rgba(255,255,255,.06)}
  .identity-grid-v12{display:grid;grid-template-columns:1fr 68px 1.15fr 68px 1fr;gap:12px;align-items:stretch}
  .identity-card-v12{position:relative;padding:22px 23px;border-radius:19px;background:rgba(255,255,255,.065);border:1px solid rgba(255,255,255,.14);overflow:hidden}
  .identity-card-v12.core{background:linear-gradient(145deg,rgba(20,160,163,.20),rgba(153,217,57,.10));border:2px solid rgba(126,224,216,.62);box-shadow:0 14px 36px rgba(0,0,0,.12)}
  .identity-card-v12 .eyebrow{font-size:9.5px;letter-spacing:.12em;text-transform:uppercase;color:#86e7df;font-weight:950;margin-bottom:8px}.identity-card-v12 h3{font-size:20px;margin:0 0 9px;color:#fff}.identity-card-v12 p{font-size:12.5px;line-height:1.58;color:#cfe1e9;margin:0}.identity-tags-v12{display:flex;gap:6px;flex-wrap:wrap;margin-top:12px}.identity-tags-v12 span{font-size:9.5px;padding:5px 7px;border-radius:999px;background:rgba(255,255,255,.07);border:1px solid rgba(255,255,255,.12);color:#d7e8ed}.identity-arrow-v12{display:grid;place-items:center;color:#78ddd5;font-size:32px}.identity-bottom-v12{margin-top:15px;text-align:center;font-size:13px;color:#d6e7ed}.identity-bottom-v12 b{color:#9ee9e2}
  .questions-v12{padding:68px 0;background:#fff;border-top:1px solid #e3ebef;border-bottom:1px solid #e3ebef}.questions-head-v12{display:flex;justify-content:space-between;gap:28px;align-items:end;margin-bottom:22px}.questions-head-v12 p{margin:0;max-width:760px;color:var(--muted);font-size:14px;line-height:1.65}.question-grid-v12{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.question-v12{position:relative;padding:21px 19px;border-radius:18px;border:1px solid var(--line);background:linear-gradient(160deg,#fff,#f7fafc);min-height:240px;box-shadow:0 8px 24px rgba(12,35,64,.04)}.question-v12:before{content:"";position:absolute;left:0;top:0;width:100%;height:3px;background:linear-gradient(90deg,var(--teal),#8cd95a)}.question-v12 .qnum{font-size:10px;color:var(--teal);font-weight:950;letter-spacing:.08em}.question-v12 h3{font-size:19px;margin:8px 0 9px;color:var(--navy)}.question-v12 .qtext{font-size:13px;line-height:1.58;color:#3f5666}.question-v12 .qmethod{margin-top:13px;padding-top:12px;border-top:1px solid #e5ecef;font-size:10.5px;color:#657a87;line-height:1.5}.question-v12 .qmethod b{color:#2b5268}.pillars-v12{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:17px}.pillar-v12{padding:14px 16px;border-radius:14px;background:#eff7f8;border:1px solid #dae9ec}.pillar-v12 b{display:block;font-size:13px;color:#173f59}.pillar-v12 span{display:block;font-size:10.5px;color:#607784;line-height:1.45;margin-top:3px}.question-note-v12{margin-top:14px;padding:13px 16px;border-left:4px solid var(--teal);background:#f8fbfc;border-radius:0 12px 12px 0;color:#567080;font-size:12px;line-height:1.55}
  .operating-model-v12{margin-top:30px;padding-top:28px;border-top:1px solid var(--line)}.operating-head-v12{display:flex;justify-content:space-between;gap:20px;align-items:end;margin-bottom:18px}.operating-head-v12 p{max-width:690px;margin:0;color:var(--muted);font-size:13px;line-height:1.55}.ownership-ladder-v12{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.ownership-step-v12{position:relative;padding:15px 12px;border:1px solid #dce8ec;border-radius:14px;background:#fbfdfe;min-height:138px}.ownership-step-v12:not(:last-child):after{content:'→';position:absolute;right:-11px;top:52px;z-index:2;color:#69cfc8;font-weight:950;font-size:18px}.ownership-step-v12 .snum{font-size:9px;letter-spacing:.09em;color:var(--teal);font-weight:950}.ownership-step-v12 b{display:block;margin:7px 0 5px;font-size:13px;color:var(--navy)}.ownership-step-v12 span{display:block;font-size:10.5px;line-height:1.45;color:#607582}.quality-grid-v12{display:grid;grid-template-columns:1.08fr .92fr;gap:14px;margin-top:15px}.quality-card-v12{border:1px solid var(--line);border-radius:17px;background:#fff;padding:19px}.quality-card-v12 h4{font-size:17px;color:var(--navy);margin-bottom:10px}.quality-list-v12{display:grid;grid-template-columns:1fr 1fr;gap:7px}.quality-item-v12{padding:9px 10px;border-radius:10px;background:#f6fafb;border:1px solid #e3ecef;font-size:10.5px;color:#526c7a}.outcome-list-v12{display:grid;gap:8px}.outcome-v12{display:grid;grid-template-columns:29px 1fr;gap:9px;align-items:start}.outcome-v12 i{font-style:normal;width:29px;height:29px;border-radius:9px;display:grid;place-items:center;background:#eef8f7;color:#158f94;font-size:10px;font-weight:950}.outcome-v12 b{display:block;font-size:12px;color:#26495e}.outcome-v12 span{display:block;font-size:10.5px;color:#667b88;margin-top:2px}.credit-v12{margin-top:14px;padding:12px 14px;border-radius:12px;background:#0e3152;color:#d8e8ee;font-size:11.5px;line-height:1.55}.credit-v12 b{color:#91e7df}
  .testbed-banner-v12{margin-top:12px;padding:12px 14px;border-radius:13px;background:rgba(126,224,216,.08);border:1px solid rgba(126,224,216,.18);font-size:12px;line-height:1.55;color:#d6e8ee}.testbed-banner-v12 b{color:#92ebe3}
  @media(max-width:1100px){.identity-grid-v12{grid-template-columns:1fr}.identity-arrow-v12{transform:rotate(90deg);height:30px}.question-grid-v12{grid-template-columns:1fr 1fr}.ownership-ladder-v12{grid-template-columns:repeat(3,1fr)}.ownership-step-v12:not(:last-child):after{display:none}.pillars-v12{grid-template-columns:1fr}.quality-grid-v12{grid-template-columns:1fr}}
  @media(max-width:650px){.question-grid-v12,.ownership-ladder-v12,.quality-list-v12{grid-template-columns:1fr}.questions-head-v12,.operating-head-v12{display:block}}
  `;
  document.head.appendChild(style);

  // Make the core identity explicit in the hero.
  const premise=document.querySelector('.research-premise');
  if(premise){
    premise.innerHTML=`<span class="lang-ko"><b>Core identity.</b> 특정 탄소중립 기술 자체보다, 원천기술이 실제 장치·공정 시스템으로 전환되는 과정에서 필요한 <b>technology translation과 engineering decision-making</b>을 연구합니다.</span><span class="lang-en"><b>Core identity.</b> Rather than being defined by a particular carbon-neutral technology, the group studies <b>technology translation and engineering decision-making</b> required to turn source technologies into credible equipment and process systems.</span>`;
    premise.insertAdjacentHTML('afterend',`<div class="testbed-banner-v12"><span class="lang-ko"><b>Technology domains are testbeds.</b> e-SAF, e-CCU, CO₂-to-methanol, FDCA, hydrogen and electrolysis are proving grounds for reusable methods in equipment-aware modeling, dynamic feasibility, validation and decision support.</span><span class="lang-en"><b>Technology domains are testbeds.</b> e-SAF, e-CCU, CO₂-to-methanol, FDCA, hydrogen and electrolysis are proving grounds for reusable methods in equipment-aware modeling, dynamic feasibility, validation and decision support.</span></div>`);
  }

  // Reframe the translation framework: the first block is the testbed/input, not the group's identity.
  const methodHeading=document.querySelector('.methodology-map .methodology-head h3');
  if(methodHeading) methodHeading.innerHTML='<span class="lang-ko">기술은 바뀌어도, 연구질문과 방법론은 축적됩니다.</span><span class="lang-en">Technologies change; research questions and methods accumulate.</span>';
  const methodLead=document.querySelector('.methodology-map .methodology-head p');
  if(methodLead) methodLead.innerHTML='<span class="lang-ko">원천기술과 응용 도메인을 입력으로 받아 장치 물리 → 공정·운전 모델 → 검증·평가 → 설계·scale-up 의사결정으로 번역하는 것이 E2P의 핵심입니다.</span><span class="lang-en">E2P takes source technologies and application domains as inputs, then translates them through equipment physics, process/operation models and validation into design and scale-up decisions.</span>';
  const methodSteps=[...document.querySelectorAll('.methodology-grid .method-step')];
  if(methodSteps[0]){
    const n=methodSteps[0].querySelector('.n');if(n)n.textContent='01 · TECHNOLOGY TESTBED';
    const b=methodSteps[0].querySelector('b');if(b)b.innerHTML='<span class="lang-ko">원천기술·응용 도메인</span><span class="lang-en">Source technology & domain</span>';
    const s=methodSteps[0].querySelector('span:last-child');if(s)s.textContent='e-SAF · e-CCU · methanol · FDCA · H₂ / electrolysis';
  }
  if(methodSteps[1]){const n=methodSteps[1].querySelector('.n');if(n)n.textContent='02 · EQUIPMENT REALITY'}
  if(methodSteps[2]){const n=methodSteps[2].querySelector('.n');if(n)n.textContent='03 · PROCESS & OPERATION'}
  if(methodSteps[3]){const n=methodSteps[3].querySelector('.n');if(n)n.textContent='04 · EVIDENCE & CREDIBILITY'}
  if(methodSteps[4]){const n=methodSteps[4].querySelector('.n');if(n)n.textContent='05 · ENGINEERING DECISION'}

  // Insert an identity translation band immediately after the hero.
  const hero=document.querySelector('#home');
  if(hero&&!document.querySelector('#research-identity-v12')){
    hero.insertAdjacentHTML('afterend',`<section class="identity-v12" id="research-identity-v12"><div class="shell"><div class="identity-grid-v12">
      <article class="identity-card-v12"><div class="eyebrow"><span class="lang-ko">APPLICATION LAYER · TESTBEDS</span><span class="lang-en">APPLICATION LAYER · TESTBEDS</span></div><h3><span class="lang-ko">탄소중립 기술은 검증 무대</span><span class="lang-en">Carbon-neutral technologies as testbeds</span></h3><p><span class="lang-ko">e-SAF, e-CCU, CO₂-to-methanol, FDCA, hydrogen/electrolysis는 연구그룹을 규정하는 단일 도메인이 아니라, 동일한 시스템 방법론을 반복 검증하고 확장하는 응용 환경입니다.</span><span class="lang-en">e-SAF, e-CCU, CO₂-to-methanol, FDCA and hydrogen/electrolysis are application environments used to test and extend a common systems methodology.</span></p><div class="identity-tags-v12"><span>e-SAF</span><span>e-CCU</span><span>CO₂-to-MeOH</span><span>FDCA</span><span>H₂</span></div></article>
      <div class="identity-arrow-v12">→</div>
      <article class="identity-card-v12 core"><div class="eyebrow">CORE RESEARCH IDENTITY</div><h3>Technology Translation & Engineering Decision-Making</h3><p><span class="lang-ko">장치의 실제 물리·성능·열화·운전 제약을 공정 수준의 모델과 운전영역으로 끌어올리고, 설계자료와 실증 데이터를 통해 신뢰성을 검증한 뒤 실제 엔지니어링 판단으로 연결합니다.</span><span class="lang-en">We lift real equipment physics, performance, degradation and operating constraints into process-level models and feasible operating regions, validate credibility with engineering and demonstration data, and translate the evidence into engineering decisions.</span></p><div class="identity-tags-v12"><span>Equipment-aware PSE</span><span>Dynamic feasibility</span><span>Model credibility</span><span>Decision relevance</span></div></article>
      <div class="identity-arrow-v12">→</div>
      <article class="identity-card-v12"><div class="eyebrow">DECISION LAYER · OUTPUT</div><h3><span class="lang-ko">연구의 끝은 모델이 아니라 결정</span><span class="lang-en">The endpoint is a decision, not a model</span></h3><p><span class="lang-ko">설계 기준, operating envelope, 장치 사양, scale-up, 운전 정책, 기술 선택과 배치 판단이 연구 결과의 최종 출력입니다.</span><span class="lang-en">Design basis, operating envelope, equipment specification, scale-up, operating policy, technology selection and deployment are the final outputs.</span></p><div class="identity-tags-v12"><span>Design basis</span><span>Operability</span><span>Scale-up</span><span>Deployment</span></div></article>
    </div><div class="identity-bottom-v12"><b>Equipment-to-Process Systems Group</b> · <span class="lang-ko">방법론 브랜드: Equipment-aware Process Systems Engineering</span><span class="lang-en">Methodology brand: Equipment-aware Process Systems Engineering</span></div></div></section>`);
  }

  // Research questions: clarify question ownership rather than tool territory.
  const research=document.querySelector('#research');
  if(research&&!document.querySelector('#research-questions-v12')){
    research.insertAdjacentHTML('afterend',`<section class="questions-v12" id="research-questions-v12"><div class="shell"><div class="questions-head-v12"><div><div class="kicker"><span class="lang-ko">핵심 연구질문</span><span class="lang-en">Core Research Questions</span></div><h2><span class="lang-ko">도구가 아니라 질문을 소유합니다.</span><span class="lang-en">We own questions, not software territories.</span></h2></div><p><span class="lang-ko">Aspen, HYSYS, COMSOL, Python, AI/ML, LCA와 TEA는 목적이 아니라 필요한 질문을 해결하기 위한 수단입니다. 연구의 novelty는 plant fidelity, operability, model credibility와 실제 의사결정에서 나옵니다.</span><span class="lang-en">Aspen, HYSYS, COMSOL, Python, AI/ML, LCA and TEA are tools selected for the question. Novelty is sought in plant fidelity, operability, model credibility and decision relevance.</span></p></div>
      <div class="question-grid-v12">
        <article class="question-v12"><div class="qnum">Q1 · CROSS-SCALE FIDELITY</div><h3><span class="lang-ko">어떤 장치 물리를 공정모델에 보존해야 하는가?</span><span class="lang-en">Which equipment physics must survive into the process model?</span></h3><div class="qtext"><span class="lang-ko">성능맵, 열·물질전달, 압력강하, 열화와 비이상 거동 중 무엇이 plant-level KPI와 설계 경계를 실제로 바꾸는지 규명합니다.</span><span class="lang-en">Determine which performance maps, transport effects, pressure drop, degradation and non-idealities materially alter plant-level KPIs and design boundaries.</span></div><div class="qmethod"><b>Typical methods</b><br>equipment model · ROM/gray-box · CFD/multiphysics interface · PFD/HMB</div></article>
        <article class="question-v12"><div class="qnum">Q2 · MODEL CREDIBILITY</div><h3><span class="lang-ko">어디까지 믿을 수 있는 모델인가?</span><span class="lang-en">Where is the model credible?</span></h3><div class="qtext"><span class="lang-ko">설계문서, 독립 재계산, 실증·운전 데이터를 이용해 validity domain, uncertainty와 source of truth를 명확히 정의합니다.</span><span class="lang-en">Use engineering documents, independent recalculation and demonstration/operating data to establish source of truth, validity domains and uncertainty.</span></div><div class="qmethod"><b>Typical methods</b><br>verification · validation · data reconciliation · uncertainty · model update</div></article>
        <article class="question-v12"><div class="qnum">Q3 · DYNAMIC FEASIBILITY</div><h3><span class="lang-ko">정상상태 최적점은 실제 운전에서도 가능한가?</span><span class="lang-en">Is the steady-state optimum dynamically feasible?</span></h3><div class="qtext"><span class="lang-ko">가변 원료·재생전력, 부분부하, 열화, startup/shutdown에서 장치 제약이 operating envelope와 제어 가능성을 어떻게 바꾸는지 분석합니다.</span><span class="lang-en">Quantify how variable feed/power, part load, degradation and startup/shutdown reshape operating envelopes and controllability.</span></div><div class="qmethod"><b>Typical methods</b><br>dynamic simulation · operability · control · performance maps · scenario analysis</div></article>
        <article class="question-v12"><div class="qnum">Q4 · DECISION RELEVANCE</div><h3><span class="lang-ko">더 정교한 모델이 실제 결정을 바꾸는가?</span><span class="lang-en">Does additional fidelity change the engineering decision?</span></h3><div class="qtext"><span class="lang-ko">모델 복잡도를 늘리는 것 자체보다 설계, scale-up, CAPEX/OPEX, 탄소저감 또는 기술 선택의 결론이 달라지는 지점을 찾습니다.</span><span class="lang-en">Rather than maximizing model complexity, identify when additional fidelity changes design, scale-up, CAPEX/OPEX, carbon or technology-selection decisions.</span></div><div class="qmethod"><b>Typical methods</b><br>optimization · TEA/LCA · sensitivity · decision layer · technology assessment</div></article>
      </div>
      <div class="pillars-v12"><div class="pillar-v12"><b>1. Equipment-aware Performance Modeling</b><span><span class="lang-ko">vendor/datasheet/performance map과 process model의 경계조건 정의</span><span class="lang-en">Define interfaces between equipment performance information and process models.</span></span></div><div class="pillar-v12"><b>2. Dynamic & Flexible Operation</b><span><span class="lang-ko">가변부하·열화·기동정지 조건에서 동특성과 운전 가능영역 분석</span><span class="lang-en">Analyze dynamics and feasible operation under variable load, degradation and transitions.</span></span></div><div class="pillar-v12"><b>3. Model-based Operational Intelligence</b><span><span class="lang-ko">물리모델 + 운전데이터 + AI/ML을 상태·성능 예측과 최적 운전 의사결정으로 연결</span><span class="lang-en">Combine physics, operating data and AI/ML for state/performance prediction and operating decisions.</span></span></div></div>
      <div class="question-note-v12"><span class="lang-ko"><b>Research boundary.</b> 고유 연구영역은 특정 software나 단일 공정이 아니라, 다른 연구자가 만든 촉매·실험·장치 결과를 실제 공정 설계·운전 의사결정으로 번역하는 interface ownership에 있습니다.</span><span class="lang-en"><b>Research boundary.</b> The distinctive territory is not a particular software package or process; it is ownership of the interface that translates catalyst, experimental and equipment results into process design and operational decisions.</span></div>
    </div></section>`);
  }

  // Keep institutional programs clearly framed as proving grounds, not the identity itself.
  const programHead=document.querySelector('#krict-programs .program-head-v11 h2');
  if(programHead) programHead.innerHTML='<span class="lang-ko">대형 과제는 연구 정체성 자체가 아니라, 방법론을 실제 scale에서 검증하는 무대입니다.</span><span class="lang-en">Large programs are proving grounds for the methodology, not the identity itself.</span>';
  const programDesc=document.querySelector('#krict-programs .program-head-v11 p');
  if(programDesc) programDesc.innerHTML='<span class="lang-ko">Global TOP, 기관 기본사업과 PI 독립연구는 서로 다른 목적의 portfolio입니다. 공통점은 각 기술을 testbed로 삼아 장치 현실 → 공정·운전 모델 → 검증 → engineering decision이라는 동일한 E2P 연구질문을 반복 검증한다는 점입니다.</span><span class="lang-en">Global TOP, the institutional basic program and the PI-led independent track serve different purposes. Their common role is to test the same E2P questions—from equipment reality through process/operation models and validation to engineering decisions—across different technologies.</span>';

  // Add a concrete ownership-to-independence operating model to the research training section.
  const joinCard=document.querySelector('#join .white-card');
  if(joinCard&&!joinCard.querySelector('.operating-model-v12')){
    const opportunities=joinCard.querySelector('.opportunities-v11');
    const block=document.createElement('div');
    block.className='operating-model-v12';
    block.innerHTML=`<div class="operating-head-v12"><div><div class="kicker"><span class="lang-ko">연구 운영 모델</span><span class="lang-en">Research Operating Model</span></div><h3><span class="lang-ko">Ownership → Independence</span><span class="lang-en">Ownership → Independence</span></h3></div><p><span class="lang-ko">신규 연구자를 기존 과제의 지원인력으로 배치하기보다, source of truth를 재현하고 검증한 뒤 하나의 interface와 연구질문을 독립적으로 소유하도록 단계적으로 권한을 이전합니다.</span><span class="lang-en">Rather than assigning researchers as general project support, responsibility is transferred step by step—from reproducing the source of truth to independently owning an interface and research question.</span></p></div>
      <div class="ownership-ladder-v12"><div class="ownership-step-v12"><div class="snum">01 · FRAME</div><b><span class="lang-ko">기준을 명확히 한다</span><span class="lang-en">Define the frame</span></b><span><span class="lang-ko">source of truth · 연구질문 · 검증기준 · 파일/코드 표준</span><span class="lang-en">source of truth · question · validation criteria · file/code standards</span></span></div><div class="ownership-step-v12"><div class="snum">02 · REPRODUCE</div><b><span class="lang-ko">독립 재현한다</span><span class="lang-en">Reproduce independently</span></b><span><span class="lang-ko">코드·모델을 직접 실행하고 물질수지·식·결과를 별도로 계산</span><span class="lang-en">run the model and independently recalculate balances, equations and outputs</span></span></div><div class="ownership-step-v12"><div class="snum">03 · CHALLENGE</div><b><span class="lang-ko">가정과 오류를 검증한다</span><span class="lang-en">Challenge assumptions</span></b><span><span class="lang-ko">오류 발견, 가정 추적, validity domain과 불확실성 기록</span><span class="lang-en">identify errors, trace assumptions, document validity and uncertainty</span></span></div><div class="ownership-step-v12"><div class="snum">04 · OWN</div><b><span class="lang-ko">하나의 interface를 소유한다</span><span class="lang-en">Own an interface</span></b><span><span class="lang-ko">장치–공정, 데이터–모델, 운전–의사결정 중 명확한 기술 경계</span><span class="lang-en">a defined equipment–process, data–model or operation–decision interface</span></span></div><div class="ownership-step-v12"><div class="snum">05 · DECIDE</div><b><span class="lang-ko">다음 분석을 제안한다</span><span class="lang-en">Propose the next analysis</span></b><span><span class="lang-ko">PI 지시가 아니라 본인이 계산·실험·모델 확장을 제안</span><span class="lang-en">the researcher proposes the next calculation, experiment or model extension</span></span></div><div class="ownership-step-v12"><div class="snum">06 · DEFINE</div><b><span class="lang-ko">다음 문제를 정의한다</span><span class="lang-en">Define the next question</span></b><span><span class="lang-ko">첫 연구의 한계에서 후속 질문을 선택하고 proposal로 발전</span><span class="lang-en">select a follow-on question from the first study's limitations and develop it into a proposal</span></span></div></div>
      <div class="quality-grid-v12"><article class="quality-card-v12"><h4><span class="lang-ko">우리가 먼저 보는 연구 품질</span><span class="lang-en">What we evaluate first</span></h4><div class="quality-list-v12"><div class="quality-item-v12"><b>Reproducibility</b><br><span class="lang-ko">동일 결과를 독립적으로 재현할 수 있는가</span><span class="lang-en">Can the result be independently reproduced?</span></div><div class="quality-item-v12"><b>Independent recalculation</b><br><span class="lang-ko">핵심 식·수지·KPI를 별도 계산으로 확인했는가</span><span class="lang-en">Were key equations, balances and KPIs checked independently?</span></div><div class="quality-item-v12"><b>Error discovery</b><br><span class="lang-ko">기존 결과의 오류 발견을 진도 지연이 아니라 성과로 평가</span><span class="lang-en">Finding an error in existing work is treated as progress, not delay.</span></div><div class="quality-item-v12"><b>Traceability</b><br><span class="lang-ko">가정·입력·version·source를 추적할 수 있는가</span><span class="lang-en">Are assumptions, inputs, versions and sources traceable?</span></div><div class="quality-item-v12"><b>Reusable interface</b><br><span class="lang-ko">다음 연구자가 다시 쓸 수 있는 코드·모델·데이터 구조인가</span><span class="lang-en">Can another researcher reuse the code, model or data interface?</span></div><div class="quality-item-v12"><b>Decision relevance</b><br><span class="lang-ko">어떤 설계·운전 판단을 바꾸는지 설명할 수 있는가</span><span class="lang-en">Can the researcher explain which engineering decision changes?</span></div></div></article>
      <article class="quality-card-v12"><h4><span class="lang-ko">연구자가 남겨야 할 자산</span><span class="lang-en">What a researcher should leave with</span></h4><div class="outcome-list-v12"><div class="outcome-v12"><i>1</i><div><b><span class="lang-ko">Flagship research question</span><span class="lang-en">Flagship research question</span></b><span><span class="lang-ko">본인이 설명하고 방어할 수 있는 독립 연구축</span><span class="lang-en">an independent question the researcher can explain and defend</span></span></div></div><div class="outcome-v12"><i>2</i><div><b><span class="lang-ko">Lead-author publication</span><span class="lang-en">Lead-author publication</span></b><span><span class="lang-ko">단순 지원업무가 아닌 본인 연구사이클의 공개 성과</span><span class="lang-en">a public output from a research cycle they actually own</span></span></div></div><div class="outcome-v12"><i>3</i><div><b><span class="lang-ko">Reusable model / code / data asset</span><span class="lang-en">Reusable model / code / data asset</span></b><span><span class="lang-ko">후속 인력과 과제가 재사용할 수 있는 팀 자산</span><span class="lang-en">a team asset reusable by later researchers and projects</span></span></div></div><div class="outcome-v12"><i>4</i><div><b><span class="lang-ko">IP where technically justified</span><span class="lang-en">IP where technically justified</span></b><span><span class="lang-ko">실제 발명 기여가 있을 때 inventorship를 연구성과로 연결</span><span class="lang-en">inventorship linked to genuine inventive contribution</span></span></div></div><div class="outcome-v12"><i>5</i><div><b><span class="lang-ko">External technical visibility</span><span class="lang-en">External technical visibility</span></b><span><span class="lang-ko">학회·공동연구·산업미팅에서 자신의 기술을 직접 대표</span><span class="lang-en">represent their own technical work in conferences, collaborations and industry meetings</span></span></div></div></div></article></div>
      <div class="credit-v12"><b><span class="lang-ko">Credit principle.</span><span class="lang-en">Credit principle.</span></b> <span class="lang-ko">학생·계약직을 과제 지원인력으로만 보지 않습니다. 저자권과 발명자권은 실제 지적·기술적 기여를 기준으로 하고, 역할 경계는 가능한 경우 CRediT taxonomy와 명시적 ownership으로 사전에 정리합니다.</span><span class="lang-en">Researchers are not treated merely as project support. Authorship and inventorship follow substantive intellectual and technical contribution, with role boundaries clarified through explicit ownership and, where useful, the CRediT taxonomy.</span></div>`;
    if(opportunities) joinCard.insertBefore(block,opportunities); else joinCard.appendChild(block);
  }

  // Refine the join headline so the public recruiting message matches the research identity.
  const join=document.querySelector('#join');
  if(join){
    const h2=join.querySelector('h2');
    if(h2) h2.innerHTML='<span class="lang-ko">기술을 시스템으로 번역하고, 그 과정에서 자기 연구축을 소유하는 연구자를 키웁니다.</span><span class="lang-en">Training researchers who translate technologies into systems and own a research axis in the process.</span>';
  }

  // Slightly sharpen PI biography to connect the doctoral thesis, industrial experience and current identity.
  const bio=document.querySelector('#pi-panel .bio-block')||document.querySelector('#people-detail .bio-block');
  if(bio){
    const statement=bio.querySelector('.statement');
    if(statement) statement.innerHTML='<span class="lang-ko">연구의 연속성: 저 TRL 기술의 실현 가능성과 평가 기준을 묻던 학위연구 → 산업 플랜트에서 장치·BOP·설계 기준을 체득한 경험 → 현재의 equipment-aware technology translation과 engineering decision-making.</span><span class="lang-en">Research continuity: doctoral work on feasibility and evaluation criteria for low-TRL technologies → industrial experience with equipment, BOP and design basis → current equipment-aware technology translation and engineering decision-making.</span>';
  }

  // Meta description follows the final identity.
  let desc=document.querySelector('meta[name="description"]');
  if(desc) desc.content='Han Sol Jung Research Group at KRICT. Equipment-aware Process Systems Engineering: technology translation and engineering decision-making from equipment physics and operating data to credible process models, dynamic feasibility, scale-up and deployment.';
  document.title='E2P Systems Group | Han Sol Jung · KRICT';
})();