(async()=>{
  const baseText=await (await fetch('site-v10.js?rev=20260811v11base',{cache:'no-store'})).text();
  const baseRun=(0,eval)(baseText);
  if(baseRun&&typeof baseRun.then==='function') await baseRun;

  const style=document.createElement('style');
  style.textContent=`
    .institutional-programs-v11{padding:72px 0;background:linear-gradient(180deg,#f4f9fb 0%,#fff 100%);border-top:1px solid #e1ebef;border-bottom:1px solid #e1ebef}
    .program-head-v11{display:flex;justify-content:space-between;gap:28px;align-items:end;margin-bottom:24px}.program-head-v11 p{max-width:770px;margin:0;color:var(--muted);font-size:15px;line-height:1.65}.program-head-v11 h2{margin:5px 0 9px}
    .program-grid-v11{display:grid;grid-template-columns:1fr 1fr;gap:18px}.program-card-v11{position:relative;background:#fff;border:1px solid var(--line);border-radius:22px;padding:25px;box-shadow:0 10px 30px rgba(13,45,70,.055);overflow:hidden}.program-card-v11:before{content:"";position:absolute;left:0;top:0;width:100%;height:4px;background:linear-gradient(90deg,var(--teal),#8dd95b)}.program-label-v11{display:flex;align-items:center;gap:8px;flex-wrap:wrap;font-size:10px;letter-spacing:.08em;text-transform:uppercase;font-weight:950;color:var(--teal)}.program-pill-v11{font-size:9px;letter-spacing:.04em;padding:5px 8px;border-radius:999px;background:#eef8f7;border:1px solid #d8ecea;color:#276e73}.program-card-v11 h3{font-size:23px;margin:10px 0 8px;color:var(--navy)}.program-card-v11>p{font-size:14px;color:var(--muted);line-height:1.6}.program-flow-v11{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin:17px 0}.program-flow-v11 span{display:grid;place-items:center;min-height:52px;padding:7px;border-radius:11px;background:#f5f9fb;border:1px solid #e0eaef;color:#315467;font-size:10.5px;font-weight:850;text-align:center;line-height:1.3}.program-role-v11{margin-top:14px;padding-top:13px;border-top:1px solid #e8eef1}.program-role-v11 b{display:block;font-size:11px;color:#163c59;margin-bottom:6px}.program-role-v11 .member-tags{margin-top:0}.independent-track-v11{margin-top:18px;display:grid;grid-template-columns:160px 1fr auto;gap:18px;align-items:center;padding:19px 21px;border-radius:18px;background:#0f3153;color:#fff;border:1px solid rgba(255,255,255,.08)}.independent-track-v11 .track-label{font-size:10px;letter-spacing:.1em;color:#83e4dc;font-weight:950;text-transform:uppercase}.independent-track-v11 b{display:block;font-size:17px;margin-top:5px}.independent-track-v11 p{margin:0;color:#d2e3eb;font-size:12.5px;line-height:1.55}.independent-track-v11 .track-badge{white-space:nowrap;padding:8px 11px;border-radius:999px;background:rgba(126,224,216,.10);border:1px solid rgba(126,224,216,.25);font-size:10px;color:#b6eee8;font-weight:850}.center-context-v11{margin-top:16px;display:flex;align-items:center;gap:10px;flex-wrap:wrap;padding:13px 16px;border-radius:14px;background:#f8fbfc;border:1px solid #e0eaee}.center-context-v11>strong{font-size:11px;color:var(--navy);margin-right:4px}.center-context-v11 a{margin-left:auto;font-size:11px;font-weight:850;color:var(--teal);text-decoration:none}
    .venture-section-v11{margin:22px 0 0;padding-top:22px;border-top:1px solid var(--line)}.venture-grid-v11{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:14px}.venture-card-v11{position:relative;border:1px solid var(--line);border-radius:18px;padding:20px;background:linear-gradient(145deg,#fff,#f7fafc);overflow:hidden}.venture-card-v11:after{content:"";position:absolute;right:-38px;top:-45px;width:125px;height:125px;border-radius:50%;border:22px solid rgba(20,160,163,.055)}.venture-card-v11 .venture-meta{font-size:9.5px;letter-spacing:.08em;text-transform:uppercase;font-weight:950;color:var(--teal)}.venture-card-v11 h4{font-size:22px;margin:7px 0 8px;color:var(--navy)}.venture-card-v11 p{font-size:13px;color:var(--muted);line-height:1.58;position:relative;z-index:1}.venture-ip-v11{margin-top:12px;padding:10px 12px;border-radius:11px;background:#eef6f8;border:1px solid #dbe9ed;font-size:11px;color:#3c6071}.venture-card-v11 a{display:inline-block;margin-top:11px;font-size:11px;color:var(--teal);font-weight:850;text-decoration:none;position:relative;z-index:1}.history-note-v11{margin-top:10px;font-size:10.5px;color:#748690}
    .collaborator-v11 .avatar-fallback-v11{height:136px;border-radius:14px;background:linear-gradient(145deg,#0e3658,#1b7782);display:grid;place-items:center;color:#fff;font-size:31px;font-weight:950;letter-spacing:-.05em;margin-bottom:13px}.collaborator-v11 .role-pill{display:inline-flex}.collaborator-v11 p{font-size:13px;line-height:1.55}.collab-role-v11{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.collab-role-v11 span{font-size:9.5px;font-weight:850;color:#356477;background:#f0f7f8;border:1px solid #dcebed;border-radius:999px;padding:5px 7px}
    .opportunities-v11{margin-top:28px;padding-top:28px;border-top:1px solid var(--line)}.op-header-v11{display:flex;justify-content:space-between;gap:18px;align-items:end;margin-bottom:17px}.op-header-v11 h3{font-size:25px;margin:4px 0}.op-header-v11 p{max-width:680px;color:var(--muted);font-size:13px;line-height:1.55;margin:0}.op-tabs-v11{display:flex;gap:8px;flex-wrap:wrap;margin:13px 0 16px}.op-tab-v11{appearance:none;border:1px solid var(--line);background:#fff;border-radius:999px;min-height:39px;padding:0 14px;color:#405969;font-size:11px;font-weight:850;cursor:pointer}.op-tab-v11.active{background:var(--navy);border-color:var(--navy);color:#fff}.op-panel-v11{display:none}.op-panel-v11.active{display:block}.op-box-v11{display:grid;grid-template-columns:1.05fr .95fr;gap:14px}.op-card-v11{border:1px solid var(--line);border-radius:17px;background:#fbfdfe;padding:19px}.op-status-v11{display:inline-flex;align-items:center;gap:7px;font-size:10px;font-weight:900;color:#267257;background:#edf8f2;border:1px solid #cfe7da;border-radius:999px;padding:6px 9px}.status-dot-v11{width:7px;height:7px;border-radius:50%;background:#39a76c}.op-card-v11 h4{font-size:18px;color:var(--navy);margin:11px 0 7px}.op-card-v11 p{font-size:13px;color:var(--muted);line-height:1.58}.route-list-v11{display:grid;gap:8px;margin-top:12px}.route-v11{display:grid;grid-template-columns:34px 1fr;gap:9px;align-items:start;padding:9px 10px;border-radius:11px;background:#fff;border:1px solid #e3ebef}.route-v11 b{display:grid;place-items:center;width:30px;height:30px;border-radius:9px;background:#eef7f7;color:#168f94;font-size:10px}.route-v11 strong{display:block;font-size:12px;color:#284a60}.route-v11 span{display:block;font-size:10.5px;color:var(--muted);margin-top:2px}.contact-v11{background:linear-gradient(145deg,#0e3152,#145e72);color:#fff!important;border:0}.contact-v11 h4,.contact-v11 strong{color:#fff}.contact-v11 p,.contact-v11 span{color:#d5e7ed}.contact-email-v11{display:inline-flex;margin-top:10px;padding:9px 12px;border-radius:10px;background:#fff;color:#0e3152!important;text-decoration:none;font-weight:900;font-size:12px}.op-links-v11{display:flex;gap:8px;flex-wrap:wrap;margin-top:13px}.op-links-v11 a{display:inline-flex;align-items:center;min-height:36px;padding:0 11px;border-radius:9px;border:1px solid #d9e6ea;color:#276270;background:#fff;text-decoration:none;font-size:10.5px;font-weight:850}
    @media(max-width:980px){.program-head-v11{display:block}.program-grid-v11,.venture-grid-v11,.op-box-v11{grid-template-columns:1fr}.independent-track-v11{grid-template-columns:1fr}.center-context-v11 a{margin-left:0}.op-header-v11{display:block}}
    @media(max-width:600px){.program-flow-v11{grid-template-columns:1fr 1fr}.institutional-programs-v11{padding:52px 0}}
  `;
  document.head.appendChild(style);

  // --- KRICT institutional portfolio --------------------------------------------------
  if(!document.querySelector('#krict-programs')){
    const programs=`<section class="institutional-programs-v11" id="krict-programs"><div class="shell">
      <div class="program-head-v11"><div><div class="kicker"><span class="lang-ko">현재 KRICT 수행 프로그램</span><span class="lang-en">Current KRICT Programs</span></div><h2><span class="lang-ko">대형 실증과 기관 기본사업을 E2P 방법론의 검증 무대로 연결합니다.</span><span class="lang-en">Institutional programs as proving grounds for the E2P methodology.</span></h2></div><p><span class="lang-ko">공식 기관 과제와 연구그룹의 독립 연구축을 구분하여 제시합니다. 대형 과제에서는 통합공정·장치·실증·전략 인터페이스를 담당하고, 독립 연구에서는 장치 현실을 공정 운전 의사결정으로 끌어올리는 핵심 방법론을 축적합니다.</span><span class="lang-en">Institutional programs and the group's independent research track are shown separately. Large programs provide integrated-process, equipment, demonstration and strategy interfaces, while the independent track develops the core methodology that transfers equipment reality into process-operational decisions.</span></p></div>
      <div class="program-grid-v11">
        <article class="program-card-v11"><div class="program-label-v11">GLOBAL TOP STRATEGIC RESEARCH GROUP <span class="program-pill-v11">CCU · 2025–2030</span></div><h3><span class="lang-ko">e-SAF 통합공정 설계·실증 및 전략 연계</span><span class="lang-en">e-SAF Integrated Process Design, Demonstration & Strategy</span></h3><p><span class="lang-ko">CO₂ 자원화를 기반으로 RWGS–FT 합성 경로, 다관식 반응기, 내부 재순환, 후속 공정과 FDCA 공정설계를 통합하며, 5세부 전략·공정 인터페이스에서 실증 및 scale-up 의사결정을 지원합니다.</span><span class="lang-en">Integrates CO₂-to-RWGS–FT synthesis, multitubular reactors, internal recycle, downstream processing and FDCA process design, supporting demonstration and scale-up decisions at the strategy/process interface of Subproject 5.</span></p><div class="program-flow-v11"><span>CO₂ / feed</span><span>RWGS · FT</span><span>Integrated process</span><span>Demo · Scale-up</span></div><div class="program-role-v11"><b><span class="lang-ko">Research-group contribution</span><span class="lang-en">Research-group contribution</span></b><div class="member-tags"><span class="member-tag">Process systems</span><span class="member-tag">Equipment-aware design</span><span class="member-tag">Demonstration</span><span class="member-tag">Strategy interface</span></div></div></article>
        <article class="program-card-v11"><div class="program-label-v11">KRICT BASIC PROGRAM <span class="program-pill-v11">DX · CARBON-NEUTRAL PROCESS</span></div><h3><span class="lang-ko">DX 활용 탄소중립 화학공정 실증 플랫폼</span><span class="lang-en">DX-enabled Carbon-Neutral Chemical Process Demonstration Platform</span></h3><p><span class="lang-ko">촉매 성능 예측과 반응·분리장치 해석을 실제 실증공정의 Physical Twin–Digital Twin 구조로 연결합니다. 연구그룹은 반응장치 동적 시뮬레이션, 장치 성능·제약 반영, model update와 운전성 평가를 중심으로 수행합니다.</span><span class="lang-en">Connects catalyst-performance prediction and reaction/separation equipment analysis to a Physical Twin–Digital Twin demonstration environment. The group focuses on dynamic equipment simulation, performance/constraint representation, model update and operability.</span></p><div class="program-flow-v11"><span>Equipment data</span><span>Dynamic model</span><span>PT ↔ DT</span><span>Operation / diagnosis</span></div><div class="program-role-v11"><b>Research-group contribution</b><div class="member-tags"><span class="member-tag">Dynamic simulation</span><span class="member-tag">Digital twin</span><span class="member-tag">Validation</span><span class="member-tag">Operability</span></div></div></article>
      </div>
      <div class="independent-track-v11"><div><div class="track-label">Independent Investigator Track</div><b><span class="lang-ko">장치 운전데이터 기반 반응설비 성능해석</span><span class="lang-en">Operating-data-driven Reaction Equipment Performance Modeling</span></b></div><p><span class="lang-ko">CO₂ 직접수소화 메탄올 공정을 testbed로 사용하여 기계설비 성능맵, 실제 운전데이터와 공정모델을 연결하는 PI 주도 독립 연구축입니다. 기관의 대형 수행 프로그램과 분리하여 연구그룹 고유의 방법론 자산을 축적합니다.</span><span class="lang-en">A PI-led independent track using CO₂-to-methanol as a testbed to connect machinery performance maps, operating data and process models. It is maintained separately from large institutional programs to build reusable methodological assets.</span></p><span class="track-badge">PI-led · independent track</span></div>
      <div class="center-context-v11"><strong><span class="lang-ko">KRICT 센터 연구축</span><span class="lang-en">KRICT center context</span></strong><span class="member-tag">LCA · TEA · GHG assessment</span><span class="member-tag">Multiphysics demonstration equipment</span><span class="member-tag">Digital twin · dynamic control</span><span class="member-tag">International certification interface</span><a href="https://www.krict.re.kr/kor/sub02_01_06.do" target="_blank" rel="noopener"><span class="lang-ko">KRICT 공식 센터 페이지 ↗</span><span class="lang-en">Official KRICT center page ↗</span></a></div>
    </div></section>`;
    const research=document.querySelector('#research');
    if(research)research.insertAdjacentHTML('afterend',programs);
  }

  // --- Entrepreneurship history: correct names and separate historical affiliation ----
  const piMain=document.querySelector('#pi-panel .pi-main')||document.querySelector('#people-detail .pi-main');
  if(piMain&&!piMain.querySelector('.venture-section-v11')){
    const venture=document.createElement('section');
    venture.className='venture-section-v11';
    venture.innerHTML=`<div class="kicker"><span class="lang-ko">초기 창업 및 공학적 실험</span><span class="lang-en">Entrepreneurship & Early Engineering Experiments</span></div><h3><span class="lang-ko">현장 문제를 장치·데이터·지식재산으로 번역한 초기 경험</span><span class="lang-en">Early experience translating field problems into devices, data and intellectual property</span></h3><div class="venture-grid-v11">
      <article class="venture-card-v11"><div class="venture-meta">Founder · Student Venture / Sole Proprietorship · Concluded</div><h4>SucSeed</h4><p><span class="lang-ko">비닐하우스 적설 문제를 기계 시스템으로 해결하려 했던 초기 창업 경험입니다. 진동 기반 제설 개념을 시제품과 지식재산으로 연결했으며, 개인사업자 형태의 학생 창업으로 종료되었습니다.</span><span class="lang-en">An early student venture addressing greenhouse snow accumulation through a mechanical system. The vibration-based snow-removal concept was translated into a prototype and IP; the sole-proprietor venture later concluded.</span></p><div class="venture-ip-v11"><b>Linked IP</b><br>KR 10-1805184 · <span class="lang-ko">비닐하우스 제설용 자동제설 로봇</span><span class="lang-en">Automatic greenhouse snow-removal robot</span></div><a href="https://www.sciencetimes.co.kr/nscvrg/view/menu/260?searchCategory=230&nscvrgSn=143769" target="_blank" rel="noopener">ScienceTimes feature ↗</a></article>
      <article class="venture-card-v11"><div class="venture-meta">Early Founding · Involvement ended in 2020</div><h4>AVALVE</h4><p><span class="lang-ko">스마트팜의 환경센싱·제어와 작물 생장 데이터를 기계학습으로 연결하는 초기 창업 과정에 참여했습니다. 정한솔의 참여는 2020년에 종료되었으며, AVALVE는 이후 별도 법인으로 성장·운영되고 있습니다.</span><span class="lang-en">Participated in the early founding phase connecting smart-farm sensing/control and crop-growth data with machine learning. Han Sol Jung's involvement ended in 2020; AVALVE subsequently developed as an independently operated corporation.</span></p><div class="venture-ip-v11"><b>Linked IP</b><br>KR 10-2307036 · <span class="lang-ko">기계 학습을 이용한 작물의 최대 생장 구현 방법</span><span class="lang-en">Method for realizing maximum crop growth using machine learning</span></div><a href="https://www.avalve.co.kr/" target="_blank" rel="noopener">AVALVE ↗</a></article>
    </div><div class="history-note-v11"><span class="lang-ko">※ 위 항목은 과거 창업·기술개발 이력이며 현재의 상업적 소속 또는 경영 참여를 의미하지 않습니다.</span><span class="lang-en">※ These are historical entrepreneurship/technology-development activities and do not indicate current commercial affiliation or management involvement.</span></div>`;
    const professional=piMain.querySelector('.professional-activities');
    if(professional)piMain.insertBefore(venture,professional); else piMain.appendChild(venture);
  }

  // --- Add Gibaek Lee to Key Collaborators -------------------------------------------
  const strategic=document.querySelector('#strategic-panel .people-cards');
  if(strategic&&![...strategic.querySelectorAll('h3')].some(h=>/Gibaek Lee|이기백/.test(h.textContent))){
    const card=document.createElement('article');
    card.className='people-card-real collaborator-v11';
    card.innerHTML=`<div class="avatar-fallback-v11">GL</div><span class="role-pill"><span class="lang-ko">핵심 협업자 · 탄소중립 전략</span><span class="lang-en">Key Collaborator · Carbon-Neutral Strategy</span></span><h3>Gibaek Lee <span class="lang-ko">· 이기백</span></h3><p><span class="lang-ko">한국화학연구원 탄소중립전략센터장. Global TOP 5세부 전략 영역에서 탄소중립 전략, LCA/GHG 감축 방법론 및 인증 연계와 관련된 협업 인터페이스를 담당합니다.</span><span class="lang-en">Director of KRICT's Carbon Neutrality Strategy Center. A strategic collaborator in Global TOP Subproject 5, with interfaces in carbon-neutral strategy, LCA/GHG-reduction methodology and certification.</span></p><div class="collab-role-v11"><span>Carbon-neutral strategy</span><span>LCA / GHG</span><span>Certification</span><span>Global TOP · Subproject 5</span></div>`;
    const sun=[...strategic.querySelectorAll('.people-card-real')].find(c=>/Sun Choi|최선/.test(c.querySelector('h3')?.textContent||''));
    if(sun&&sun.nextSibling)strategic.insertBefore(card,sun.nextSibling); else strategic.prepend(card);
  }

  // --- Recruiting / Open Positions -----------------------------------------------------
  const join=document.querySelector('#join');
  const joinCard=join?.querySelector('.white-card');
  if(joinCard&&!joinCard.querySelector('.opportunities-v11')){
    joinCard.insertAdjacentHTML('beforeend',`<div class="opportunities-v11"><div class="op-header-v11"><div><div class="kicker"><span class="lang-ko">연구 참여 기회</span><span class="lang-en">Open Positions & Collaboration</span></div><h3><span class="lang-ko">KRICT 제도 안에서 연구자와 협력자를 모집합니다.</span><span class="lang-en">Recruiting researchers and collaborators through KRICT programs.</span></h3></div><p><span class="lang-ko">채용은 한국화학연구원의 공식 공고와 승인된 인력제도를 통해 진행됩니다. 구체적인 직종과 시기는 기관 공고·과제 수요에 따라 달라지며, 관심 연구자는 관련 공고 전에도 PI에게 연구 적합성을 문의할 수 있습니다.</span><span class="lang-en">Appointments are made through official KRICT recruitment calls and approved institutional programs. Position type and timing depend on formal notices and project needs; prospective researchers may contact the PI in advance to discuss research fit.</span></p></div><div class="op-tabs-v11"><button class="op-tab-v11 active" data-optarget="op-open-v11"><span class="lang-ko">연구자 모집</span><span class="lang-en">Open Positions</span></button><button class="op-tab-v11" data-optarget="op-collab-v11"><span class="lang-ko">공동연구</span><span class="lang-en">Collaboration</span></button><button class="op-tab-v11" data-optarget="op-contact-v11">Contact</button></div>
      <div class="op-panel-v11 active" id="op-open-v11"><div class="op-box-v11"><article class="op-card-v11"><span class="op-status-v11"><span class="status-dot-v11"></span><span class="lang-ko">KRICT 공식 채용경로 활용</span><span class="lang-en">KRICT institutional recruitment routes</span></span><h4><span class="lang-ko">관심 연구자에게 열려 있는 주요 경로</span><span class="lang-en">Typical routes for prospective researchers</span></h4><div class="route-list-v11"><div class="route-v11"><b>MS+</b><div><strong><span class="lang-ko">석사후연구원</span><span class="lang-en">Post-master Researcher</span></strong><span><span class="lang-ko">공정·반응시스템 모델링, 장치 다중물리, 공정최적화 등</span><span class="lang-en">Process/reaction-system modeling, equipment multiphysics and optimization</span></span></div></div><div class="route-v11"><b>R</b><div><strong><span class="lang-ko">연수직·프로젝트 연구직</span><span class="lang-en">Research / Project Appointments</span></strong><span><span class="lang-ko">승인된 과제와 기관 공고에 따라 모집</span><span class="lang-en">Subject to approved projects and institutional calls</span></span></div></div><div class="route-v11"><b>S</b><div><strong><span class="lang-ko">학생연구원·인턴 등</span><span class="lang-en">Student Research / Internship</span></strong><span><span class="lang-ko">기관 제도 및 연구주제 적합성에 따라 운영</span><span class="lang-en">Where available through KRICT programs and research fit</span></span></div></div></div><div class="op-links-v11"><a href="https://www.krict.re.kr/recruit/hrn/Hrn_0101/01/list" target="_blank" rel="noopener"><span class="lang-ko">KRICT 채용정보 ↗</span><span class="lang-en">KRICT Recruitment ↗</span></a><a href="mailto:hsjung@krict.re.kr"><span class="lang-ko">PI에게 문의</span><span class="lang-en">Contact PI</span></a></div></article><article class="op-card-v11 contact-v11"><div class="kicker" style="color:#8ae8e0">Research Fit</div><h4><span class="lang-ko">어떤 연구자를 찾는가</span><span class="lang-en">Research profiles of interest</span></h4><p><span class="lang-ko">장치의 실제 거동을 이해하면서 공정 모델·데이터·최적화로 확장하고 싶은 연구자, 또는 화학공정 시스템을 장치 물리와 연결하고 싶은 기계·화공·데이터 배경 연구자를 환영합니다.</span><span class="lang-en">We welcome researchers who want to connect real equipment behavior with process models, data and optimization, including mechanical, chemical-process and data-oriented backgrounds.</span></p><div class="member-tags"><span class="member-tag">Equipment modeling</span><span class="member-tag">COMSOL / multiphysics</span><span class="member-tag">Aspen / process systems</span><span class="member-tag">Dynamics / control</span><span class="member-tag">AI / hybrid models</span><span class="member-tag">LCA / TEA</span></div></article></div></div>
      <div class="op-panel-v11" id="op-collab-v11"><div class="op-box-v11"><article class="op-card-v11"><h4><span class="lang-ko">공동연구 인터페이스</span><span class="lang-en">Collaboration interfaces</span></h4><p><span class="lang-ko">촉매·반응기·장치 실험 결과를 공정시스템의 설계와 운전 의사결정으로 연결하는 공동연구를 지향합니다. 공동연구에서는 데이터 전달에 그치지 않고 모델의 유효범위, scale-up 기준과 의사결정 변수를 함께 정의하는 것을 우선합니다.</span><span class="lang-en">We collaborate at interfaces that translate catalyst, reactor and equipment results into process-system design and operational decisions. Joint work emphasizes model-validity domains, scale-up criteria and decision variables rather than data transfer alone.</span></p><div class="member-tags"><span class="member-tag">Reactor / equipment</span><span class="member-tag">Process integration</span><span class="member-tag">Digital twin</span><span class="member-tag">Operability</span><span class="member-tag">Optimization</span><span class="member-tag">Sustainability assessment</span></div></article><article class="op-card-v11"><h4><span class="lang-ko">공동연구 제안 시 유용한 정보</span><span class="lang-en">Useful information for collaboration inquiries</span></h4><div class="route-list-v11"><div class="route-v11"><b>01</b><div><strong><span class="lang-ko">기술·장치와 연구질문</span><span class="lang-en">Technology / equipment and question</span></strong><span><span class="lang-ko">무엇을 실제로 의사결정해야 하는지</span><span class="lang-en">What engineering decision needs to be made</span></span></div></div><div class="route-v11"><b>02</b><div><strong><span class="lang-ko">가용 데이터와 검증 수준</span><span class="lang-en">Available data & validation level</span></strong><span>experiment · design document · pilot / plant data</span></div></div><div class="route-v11"><b>03</b><div><strong><span class="lang-ko">원하는 산출물</span><span class="lang-en">Expected output</span></strong><span>model · design basis · optimization · scale-up · paper / IP</span></div></div></div></article></div></div>
      <div class="op-panel-v11" id="op-contact-v11"><div class="op-box-v11"><article class="op-card-v11 contact-v11"><div class="kicker" style="color:#8ae8e0">Principal Investigator</div><h4>Han Sol Jung · 정한솔</h4><p><span class="lang-ko">선임연구원 · 한국화학연구원 화학공정솔루션연구센터<br>Equipment-to-Process Systems / Equipment-aware Process Systems Engineering</span><span class="lang-en">Senior Researcher · Chemical Process Solution Research Center, KRICT<br>Equipment-to-Process Systems / Equipment-aware Process Systems Engineering</span></p><a class="contact-email-v11" href="mailto:hsjung@krict.re.kr">hsjung@krict.re.kr</a></article><article class="op-card-v11"><h4><span class="lang-ko">지원·협업 문의</span><span class="lang-en">Application / collaboration inquiry</span></h4><p><span class="lang-ko">간단한 CV 또는 연구배경, 관심 연구주제와 가능한 시작 시점을 함께 보내주시면 연구그룹의 과제·연구축과의 적합성을 검토하기 쉽습니다. 공식 채용은 반드시 KRICT 공고와 절차를 따릅니다.</span><span class="lang-en">A short CV or research background, topics of interest and possible start timing are helpful for assessing fit with the group's research programs. Formal appointments must follow KRICT's official recruitment procedures.</span></p><div class="op-links-v11"><a href="https://www.krict.re.kr/kor/sub02_01_06.do" target="_blank" rel="noopener">KRICT Center ↗</a><a href="https://www.krict.re.kr/recruit/hrn/Hrn_0101/01/list" target="_blank" rel="noopener">KRICT Recruitment ↗</a></div></article></div></div>
    </div>`);
    joinCard.querySelectorAll('.op-tab-v11').forEach(btn=>btn.addEventListener('click',()=>{const root=btn.closest('.opportunities-v11');root.querySelectorAll('.op-tab-v11').forEach(b=>b.classList.remove('active'));root.querySelectorAll('.op-panel-v11').forEach(p=>p.classList.remove('active'));btn.classList.add('active');root.querySelector('#'+btn.dataset.optarget)?.classList.add('active')}));
  }

  // Correct historical venture spellings if any older strings remain in the DOM.
  document.querySelectorAll('body *').forEach(el=>{
    if(el.children.length===0&&el.textContent){
      el.textContent=el.textContent.replace(/석씨드/g,'SucSeed').replace(/어밸브/g,'AVALVE');
    }
  });
})();